---
title: "ESM 244 Lab 1"
author: "Alessandra Puig-Santana"
date: "2023-01-13"
output: html_document
---

```{r setup, include=TRUE, echo = TRUE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(here)
library(sf)
library(tmap)
```

### Read in the data

```{r}
sf_trees <- read_csv(here('data', 'sf_trees', 'sf_trees.csv'))

top_5_status <- sf_trees %>%
  group_by(legal_status) %>%
  summarize(tree_count = n()) %>%
  slice_max(tree_count, n = 5) %>% #find the valuables of this variable that is maximum and get the top 5
  arrange(-tree_count) #arrange from largest to smallest
```

### Graph
```{r}
ggplot(data = top_5_status,
       aes(x = fct_reorder(legal_status, tree_count), # we are rearranging our x-axis to be tree count instead of the legal status
           y = tree_count)) +
  geom_col() +
  labs(y = 'Tree count', x = 'Legal Status') +
  coord_flip() +
  theme_minimal()
```

### Keep observations where legal status is "Permitted site" and caretaker is "MTA"

```{r}
sf_trees$legal_status %>% unique() #this tells u the way its written, always follow it!
permitted_mta <- sf_trees %>%
  filter(legal_status == "Permitted Site" & caretaker == "MTA")
```

```{r}
blackwood_acacia <- sf_trees %>%
  filter(str_detect(species, "Blackwood Acacia")) %>%
  select(legal_status, date, latitude, longitude)

### make a plot of SF Acacia
ggplot(data = blackwood_acacia, aes(x = longitude, y = latitude)) +
  geom_point()
```

### Use tidyr::separate() to separate one column into multiple, and tidyr::unite() to rejoin
```{r}
# separate the species name and common name 
sf_trees_sep <- sf_trees %>%
  separate(species, into = c("spp_scientific", "spp_common"), sep = "::")

sf_trees_unite <- sf_trees %>%
  unite("id_status", tree_id:species, sep = '_NEW_')
```


### Make some actual maps!

```{r}
# simple features object
blackwood_acacia_sf <- blackwood_acacia %>%
  drop_na(longitude, latitude) %>%
  st_as_sf(coords = c('longitude', 'latitude'))
# coordinate reference system
st_crs(blackwood_acacia_sf) <- 4326 

ggplot(data = blackwood_acacia_sf) +
  geom_sf(color = 'darkgreen') +
  theme_minimal()
```

#### read in SF streets data
```{r}
sf_map_SF <- read_sf(here('data', 'sf_map', 'tl_2017_06075_roads.shp')) %>%
  st_transform(4326) #transforming from one coordinate system to another

st_crs(sf_map_SF)
```

### Map in ggplot
```{r}
ggplot() + 
  geom_sf(data = sf_map_SF, size = 0.1, color = 'darkgrey') +
  geom_sf(data = blackwood_acacia_sf, color = 'red', size = 0.5) +
  theme_void() +
  labs(title = 'Blackwood Acaica in San Francisco')
```

### Interactice map!
```{r}
tmap_mode('view')
tm_shape(blackwood_acacia_sf) +
  tm_dots()
```

